<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <groupId>ServidorCentral</groupId>
  <artifactId>ServidorCentral</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>Servidor Central</name>

  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
      <resource>
        <directory>src</directory>
        <excludes>
          <exclude>**/*.java</exclude>
        </excludes>
      </resource>
      <resource>
        <directory>src/servidor/imagenesCargaDatos</directory>
        <targetPath>servidor/imagenesCargaDatos</targetPath>
        <includes>
          <include>**/*.*</include>
        </includes>
      </resource>
    </resources>

    <plugins>

      <!-- Compilador -->
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <release>21</release>
        </configuration>
      </plugin>

      <plugin>
		  <groupId>com.sun.xml.ws</groupId>
		  <artifactId>jaxws-maven-plugin</artifactId>
		  <version>4.0.2</version>
	</plugin>


      <!-- Ensamblado de JARs -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>3.6.0</version>
        <executions>
          <!-- JAR del servidor -->
          <execution>
            <id>jar-servidor</id>
            <phase>package</phase>
            <goals><goal>single</goal></goals>
            <configuration>
              <finalName>ServidorCentral-Servidor</finalName>
              <archive>
                <manifest>
                  <mainClass>servidor.main</mainClass>
                </manifest>
              </archive>
              <descriptorRefs>
                <descriptorRef>jar-with-dependencies</descriptorRef>
              </descriptorRefs>
              <includes>
                <include>servidor/**</include>
              </includes>
            </configuration>
          </execution>

        </executions>
      </plugin>

    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>jakarta.xml.ws</groupId>
      <artifactId>jakarta.xml.ws-api</artifactId>
      <version>4.0.0</version>
    </dependency>
    <dependency>
      <groupId>com.sun.xml.ws</groupId>
      <artifactId>jaxws-rt</artifactId>
      <version>4.0.0</version>
    </dependency>
  </dependencies>
</project>
